name: maskgitnf_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip=23.3.1
  - pytorch==2.4.1
  - torchvision==0.17.0
  - pytorch-cuda=11.8
  - pip:
      - albumentations==1.3.1
      - einops==0.7.0
      - h5py==3.11.0
      - huggingface-hub==0.20.3
      - matplotlib==3.7.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python-headless==4.9.0.80
      - pandas==2.0.3
      - lightning==2.3.3
      - pytorch-fid==0.3.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - tensorboard==2.14.0
      - timm==0.9.12