model:
  base_learning_rate: 0.0001
  target: models.maskgit.MaskGIT
  params:
    adjust_lr_to_batch_size: false
    patch_size: 16
    num_tokens: 64
    image_size: 256
    tokenizer_config:
      folder: /work/dlclarge2/mutakeks-titok/mae_256
      checkpoint_folder: checkpoints/checkpoints/checkpoints/checkpoints/checkpoints/checkpoints/checkpoints/checkpoints/checkpoints/last.ckpt
    predictor_config:
      target: Network.transformer.MaskTransformer
      params:
        img_size: 256
        patch_size: 16
        hidden_dim: 768
        depth: 16
        heads: 8
        mlp_dim: 3072
        dropout: 0.1
        codebook_size: 4096
        num_tokens: 64
    loss_config:
      target: torch.nn.CrossEntropyLoss
      params:
        label_smoothing: 0.1
    scheduler_config:
      target: modules.schedulers.maskgit_scheduler.UnconditionalMaskGITScheduler
      params:
        default_schedule_mode: arccos
        default_num_steps: 12
        disable_bar: true
        codebook_size: 4096
        num_tokens: 16
        mask_value: 4096
data:
  target: main_pl.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: Network.Taming.data.custom_multiframe.MultiHDF5DatasetMultiFrame
      params:
        hdf5_paths_file: /work/dlcsmall2/mittal-bdd-data/video_data/train.txt
        size: 256
        num_frames: 1
    validation:
      target: Network.Taming.data.custom_multiframe.MultiHDF5DatasetMultiFrame
      params:
        hdf5_paths_file: /work/dlcsmall2/mittal-bdd-data/video_data/val.txt
        size: 256
        num_frames: 1
